poetry.lock
pyproject.toml
src/auth/config.py
src/auth/router.py
src/auth/schemas.py
src/auth/service.py
src/main.py
src/web_server/main.py

---
close #2 
<br><br>
---
- Implement GitHub OAuth login logic
- Need to define how to manage the AccessToken in upcoming pull requests.
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Implement GitHub login

---

.github/workflows/deploy.yml
Dockerfile
pyproject.toml

---
<br><br>
---
- Update deploy workflow
- Use GitHub Packages for Docker image
- Update Dockerfile (change PYTHONPATH)
- Change required python version to python3.11
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

build: Update deploy workflow and Dockerfile

---

Dockerfile

---
<br><br>
---
Remove redundant dependency install command.
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

refactor: Remove redundant dependency install command

---

Dockerfile
poetry.lock
pyproject.toml
src/auth/router.py
src/auth/service.py
src/database.py
src/main.py
src/user/repository.py
src/user/service.py

---
close #10 
<br><br>
---
Remove asyncmy package (possible unknown error with GitHub actions) and update relevant codes
Remove redundant poetry install command in Dockerfile
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

fix: Remove asyncmy package

---

src/auth/router.py
src/auth/schemas.py

---
close #12 
<br><br>
---
- Add request body for refresh and logout functions
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Add request body for refresh and logout functions

---

src/auth/service.py
src/exceptions/definitions.py
src/exceptions/handler.py
src/main.py
src/user/service.py

---
close #15 
<br><br>
---
Add custom exceptions for auth services
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Add Auth custom exceptions

---

poetry.lock
pyproject.toml
src/response/error_definitions.py
src/stat/service.py

---
close #34 
<br><br>
---
- Implement get_repositories function
- Implement get_pull_requests function
- Implement get_commits function
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Implement GitHub api using for adjudging user stat

---

src/issue/repository.py
src/issue/router.py
src/issue/schemas.py
src/issue/service.py
src/main.py
src/response/error_definitions.py
src/response/success_definitions.py
src/user/schemas.py

---
close #16 
<br><br>
---
- Implement GitHub Issue CRUD functions
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Implement issue crud functions

---

src/auth/service.py
src/user/models.py
src/user/schemas.py
src/user/service.py

---
close #42 
<br><br>
---
- Return user profile image in UserRes object
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Return user profile img in UserRes object

---

src/agent/tool.py

---
- close #49 
<br><br>
---
- Add json loader for rag prompts
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Add json file loader for loading stats as json

---

.gitignore
pyproject.toml
src/agent/tool.py

---
- close #51 
<br><br>
---
- Reinstall modules with poetry instead of pip
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

fix: Apply modules through poetry

---

src/issue/repository.py
src/issue/schemas.py
src/user/models.py
src/user/repository.py

---
close #43 
<br><br>
---
- Updates the issue assignee list to return UserRes objects instead of just user names.
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Add UserRes to issue assignee list

---

src/project/schemas.py

---
close #54 
<br><br>
---
- Add member profile image link in ProjectUserRes object
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Add member profile img in ProjectUserRes object

---

.github/workflows/deploy.yml

---
<br><br>
---
- Remove copying env file scripts (now setup env file manually)
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

build: Remove copy env file script

---

src/agent/chain.py
src/agent/prompts.py
src/agent/router.py
src/agent/schemas.py
src/agent/tool.py
src/auth/service.py
src/response/success_definitions.py
src/stat/service.py
src/user/models.py
src/user/repository.py

---
- close #46 
<br><br>
---
- Get activation data from github and trim
- Call gemini with appropriate prompts and data
- Add field to User model for stat data (json)
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Implement stat assessment with github data

---

src/issue/repository.py
src/issue/router.py
src/issue/schemas.py
src/issue/service.py

---
close #62 
<br><br>
---
- Add function to get all issues list from repository
- Add closed field in IssueRes
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Add function to get all issues from repository

---

src/issue_rescheduling/models.py
src/issue_rescheduling/repository.py
src/issue_rescheduling/router.py
src/issue_rescheduling/schemas.py
src/issue_rescheduling/service.py
src/models/__init__.py
src/project/models.py
src/response/error_definitions.py
src/response/success_definitions.py

---
> Please specify the related issue number(s), e.g., #1 
close #41 
<br><br>
---
- Implement CRUD for issue rescheduling requests
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Implement CRUD for issue rescheduling requests

---

src/user/models.py

---
close #66 
<br><br>
---
- Change field size of career
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Change field size of career

---

src/main.py

---
<br><br>
---
Add issue rescheduling router to main.py
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Add issue rescheduling router to main

---

src/issue/repository.py
src/issue/router.py
src/issue/schemas.py
src/issue/service.py
src/response/error_definitions.py

---
close #74 
<br><br>
---
-Add api for returning summary of issue states (opend, closed, all) in project
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Add api for returning summary of issue states in project

---

src/project/repository.py
src/project/router.py
src/project/schemas.py
src/project/service.py
src/project_user/repository.py

---
close #73 
<br><br>
---
- Add api for getting all projects that user owns or participates in
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Add api for getting all projects

---

src/issue/repository.py
src/issue/router.py
src/issue/schemas.py
src/issue/service.py

---
close #75 
<br><br>
---
- Change repo_fullname to project_id in issue create/update/close
- Change path variables to query parameters in issue GET apis 
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Change repo_fullname to project_id in issue CUD

---

src/auth/service.py

---
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Change cookie secure setting when redirect after GitHub login

---

src/project/schemas.py
src/project/service.py
src/response/error_definitions.py

---
- close #85 
<br><br>
---
- Add design document infos in ProjectRes schema
- Get documents from project directory 
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Implement loading file names as list when getting project

---

.github/workflows/deploy.yml
.github/workflows/restart.yml

---
<br><br>
---
- Remove redundant commands in deploy.yml
- Add restart workflow yml
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

build: Remove redundant workflow and add restart workflow

---

src/auth/schemas.py
src/project/models.py
src/project/router.py
src/project/schemas.py
src/project/service.py
src/user/models.py
src/user/schemas.py

---
close #82 
<br><br>
---
- Change discord id field type to string from int
- Make create project function work async
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

fix: Change discord_id field type to string

---

.github/workflows/restart.yml

---
<br><br>
---
- Change restart workflow name to Restart
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

chore: Change restart workflow name to Restart

---

src/config/middleware.py
src/main.py

---
<br><br>
---
- Fix CORS problems (change middleware to add_middleware in main.py for JWT token authentication)
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Update middleware to fix CORS

---

src/agent/router.py
src/issue/router.py
src/issue_rescheduling/router.py
src/project/router.py
src/user_repository/router.py

---
<br><br>
---
- Fix redirection issues in routers
- Remove "/"s
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Fix redirection issue in routers

---

src/config/middleware.py
src/response/handler.py
src/response/schemas.py

---
close #96
<br><br>
---
- Add request method, url information in ErrorResponse
- Fix CORS header issue when 401 Unauthorized
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Add request method and path info in ErrorResponse

---

src/auth/service.py
src/response/success_definitions.py

---
<br><br>
---
- Add missing parameter in update_user_response
- Add missing parameter when delete_user function
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Fix missing parmeter when update user response

---

src/config/middleware.py

---
<br><br>
---
NIM
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Add allow path for refreshtoken in middleware

---

src/auth/router.py
src/auth/service.py

---
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Implement update user

---

src/auth/service.py
src/user/service.py

---
<br><br>
---
Fix function to update 'existing' user object.
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Implement updating existing user

---

src/issue_rescheduling/repository.py

---
<br><br>
---
Fix TypeError in project_id IN clause by wrapping with list
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Fix TypeError in project_id IN clause by wrapping with list

---

src/agent/router.py

---
<br><br>
---
- Change http method (get -> post) for assess stat function
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Change http method for assess_stat()

---

src/project/service.py

---
<br><br>
---
- When listing file names from db, removed asynchronous processing.
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Remove asynchronous processing

---

src/agent/chain.py
src/agent/router.py
src/response/error_definitions.py

---
- close #108 
<br><br>
---
- Add project id to function params
- Get documents with project info
- Extract text from the documents
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

fix: Add project id when generating issues to get project info

---

src/agent/chain.py
src/agent/router.py
src/agent/schemas.py
src/agent/tool.py
src/response/error_definitions.py
src/response/success_definitions.py

---
<br><br>
---
- No needs to get request body when assessing stat
- Get selected repo infos using function in user_repository.service
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Remove request body from assess stat function

---

src/project/router.py

---
<br><br>
---
Remove await when create project(async was removed in last pr)
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Remove await when create project

---

src/config/middleware.py

---
<br><br>
---
Fix Typo in middleware exception. (exc.message to exc.title)
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Fix Typo in middleware exception

---

src/config/database.py
src/issue_rescheduling/repository.py
src/project/repository.py
src/project_user/repository.py
src/response/error_definitions.py
src/user/repository.py
src/user_repository/repository.py

---
<br><br>
---
Remove detailed error in SQLError for security
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Remove detailed error in SQLError for security

---

src/agent/chain.py
src/agent/tool.py

---
<br><br>
---
- Add handler for none project.
- Add necessary params to function (get_all_selected_repositories)
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Add necessary parameters when getting all selected repos

---

src/project/service.py

---
<br><br>
---
- If design docs is empty, delete all existing files
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Handle to delete all files when updating project info

---

src/config/middleware.py
src/response/handler.py
src/response/schemas.py

---
<br><br>
---
Fix middleware ErrorResposne missing parameters
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Fix middleware ErrorResponse missing parameters

---

src/main.py
src/response/handler.py

---
<br><br>
---
Add exception handler for `Exception`
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Add global exception handler

---

src/agent/chain.py
src/agent/tool.py
src/response/error_definitions.py

---
<br><br>
---
- Give all texts from design documents (extracted_texts, not text)
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Give full rags to generate issues

---

.github/workflows/deploy.yml

---
<br><br>
---
Remove removing container forcefully
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

build: Refactor docker compose update script

---

src/agent/chain.py
src/agent/router.py
src/agent/tool.py

---
<br><br>
---
- Stream llm response when generating initial issues
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Generate issues with streaming service

---

src/issue_rescheduling/router.py
src/issue_rescheduling/service.py
src/response/error_definitions.py

---
close #131 
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

fix: Add issue rescheduling deletion type

---

src/project/repository.py
src/project/service.py
src/project_user/repository.py

---
close #129 
<br><br>
---
Rollback create new project and project_user if error occurred
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

fix: Rollback when error occurred while create new project

---

src/agent/chain.py
src/agent/prompts.py
src/agent/router.py
src/agent/schemas.py
src/agent/tool.py
src/response/error_definitions.py
src/response/success_definitions.py

---
- close #48 
<br><br>
---
- Write new prompts to request feedback for rescheduling issue
- Get stats of team members, project infos, content of issue as rag dataset
<br><br>
---
<br><br>
---
<br><br>
---
- It is needed to call feedback function when create? or get a certain issue rescheduling model
<br><br>

feat: Get feedback for rescheduling issue from gemini

---

src/agent/chain.py
src/agent/tool.py

---
<br><br>
---
- Add print lines to check agent action
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

chore: Add log for agent action

---

src/project/schemas.py
src/project/service.py

---
close #135 
<br><br>
---
- Add Missing user id in ProjectMemberRes
- Add code for preventing create project_user with unknown user_id (Need to check if project member id exists)
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Fix logic for updating project member

---

src/agent/chain.py
src/agent/prompts.py
src/agent/router.py
src/agent/schemas.py
src/agent/tool.py

---
<br><br>
---
- User names are not essential to assign issues to each user.
- So, removed them from request format.
- Get user infos from project object
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Exclude user names when request for assigning issues

---

src/agent/chain.py
src/agent/router.py
src/agent/tool.py
src/project/service.py

---
<br><br>
---
- Update and delete files are impossible.
- The problem was timestamp in filename.
- So, removed it and add checking lines for already existing filenames
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Remove timestamp from filename

---

src/config/volume_config.py
src/main.py

---
- close #139 
<br><br>
---
- Remove paths, dirs when starting server
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Add volume config for initializing volumes of design docs

---

src/agent/chain.py
src/config/volume_config.py
src/main.py

---
<br><br>
---
- Method to get user stat from project was wrong.
- Refer project and then project_user and then user.
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Amend method to get user stat

---

src/agent/chain.py

---
<br><br>
---
- Amend parameter when call tool.recommend_assignees_for_issues()
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Amend parameter

---

src/agent/chain.py
src/agent/prompts.py
src/agent/schemas.py
src/agent/tool.py

---
- close #143 
<br><br>
---
- Get proper schedule of issues from gemini
- Return issue response with sprint number
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Add sprint number to issue info

---

src/agent/chain.py
src/agent/prompts.py
src/agent/tool.py
src/auth/service.py

---
<br><br>
---
- Add lines for checking invalid response from gemini to extract_json_dict_from_response()
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Add lines for checking invalid repsonse

---

src/agent/chain.py
src/agent/schemas.py

---
<br><br>
---
- Add classmethod that generate schemas from other object to each schema.
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

chore: Define method to generate schemas from other object

---

src/agent/chain.py
src/project/service.py

---
<br><br>
---
- Rename path of project.
- Add disappeared parameter.
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Rename document paths and add parameter

---

src/project/service.py

---
<br><br>
---
Add function to check project name duplication
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Check project name duplicated when updating project

---

src/agent/schemas.py

---
<br><br>
---
- Add missed field 'sprint' to GenerateIssueRes
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Add missed field

---

src/main.py

---
<br><br>
---
Drop database only in local environment (keep in production)
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

chore: Drop database only in local environment

---

src/project/service.py

---
<br><br>
---
Fix logic for updating project name
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Fix logic for updating project name

---

src/response/error_definitions.py

---
<br><br>
---
Change missing token error to 401 exception
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Change missing token error to 401

---

src/main.py

---
<br><br>
---
Drop design-docs only in local environment
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Drop design-docs only in local environment

---

src/agent/chain.py
src/agent/prompts.py
src/user/repository.py

---
<br><br>
---
- Amend prompts that makes gemini assign at least one developer to each issue.
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

chore: Amend prompts for assigning issues

---

src/agent/prompts.py

---
<br><br>
---
- Set assign issue prompt more clear (output must include certain fields)
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

chore: Set request contents in prompt more clear

---

src/agent/chain.py

---
<br><br>
---
- add project info when defining features
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Add necessary parameter (project_info)

---

src/agent/tool.py

---
<br><br>
---
- Removed debugging lines which is unnecessary.
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

chore: Remove debug lines

---

src/agent/prompts.py

---
<br><br>
---
- Amend prompt to generate all issues for project, not 10 tasks
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Amend prompt to generate more than 10 issues

---

src/auth/service.py
src/response/error_definitions.py
src/user_repository/repository.py

---
close #167 
<br><br>
---
Check if user has project before unregister
If user can unregister, delete user_repo before delete user
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

fix: Check project_user before unregister

---

src/issue_rescheduling/repository.py
src/issue_rescheduling/router.py
src/issue_rescheduling/schemas.py
src/issue_rescheduling/service.py
src/response/success_definitions.py

---
close #97 
<br><br>
---
Update issue according to IssueReschedulingRequest if the request was approved
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Update issue according to IssueReschedulingRequest

---

src/user/schemas.py

…info
---
close #163 
<br><br>
---
Check user category is valid when registering or updating user using pydantic
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Check user category is valid when registering or updating user

---

.github/workflows/deploy.yml

---
<br><br>
---
- Try to make deploy faster
- Enable Docker layer caching using GitHub Actions cache
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

build: Enable Docker layer caching using GitHub Actions cache

---

src/auth/service.py
src/user/service.py

---
close #174 
<br><br>
---
Update GitHub AccessToken when login
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Update GitHub accessToken when login

---

src/main.py

---
<br><br>
---
Add bot_router to app routers
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Connect bot router to app

---

src/project/service.py

---
close #156 
<br><br>
---
Fix error occurred when getting project without files
Make project directory in design_docs regardless file exists or not
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

fix: Handle project with no files

---

src/bot/router.py

---
<br><br>
---
Fix api path for bot
- get all issue (/bot/issues)
- create issue rescheduling (/bot/issue-reschedule)
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

chore: Fix api path for bot

---

src/bot/router.py
src/project/repository.py

---
<br><br>
---
Add bot router to get all issues for user
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Add bot router to get all issues for user

---

src/issue_rescheduling/repository.py

---
<br><br>
---
Fix logical issue when check issue rescheduling duplication
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Fix issue rescheduling request duplicate issue

---

src/auth/router.py
src/auth/service.py
src/user/router.py
src/user/service.py

---
close #190 
<br><br>
---
Move unregister function to user from auth and check the user has project 
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

refactor: Move unregister function to user from auth

---

src/project/repository.py
src/project/router.py
src/project/schemas.py
src/project/service.py
src/response/error_definitions.py
src/user/repository.py

---
close #196 
close #193 
<br><br>
---
Remove useless exception in both user and project repository
Move add project user logic to the project repository
Add more exception handler if object not exists
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

refactor: Refactor project api

---

src/common/util/permissions.py
src/config/middleware.py
src/issue_rescheduling/models.py
src/issue_rescheduling/schemas.py
src/issue_rescheduling/service.py
src/response/error_definitions.py

---
close #192 
close #195 
<br><br>
---
Add requester info and issue title in IssueReschedulingRes
Add permission checker for issue_rescheduling apis
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Add requester info and issue title in IssueReschedulingRes

---

src/bot/router.py

---
close #201 
<br><br>
---
Change find_projects_by_member parameter in bot
(discord_id -> user.id)
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

fix: Change find_projects_by_member parameter in bot

---

src/common/util/permissions.py
src/project/service.py
src/response/error_definitions.py

---
close #193 
<br><br>
---
Add permission checker for get_project
Remove unnecessary project existence check code
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

feat: Add permission checker for get_project

---

src/bot/router.py

---
close #200 
<br><br>
---
Add exception if project or user not found
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

fix: Add exception if project or user not found

---

src/issue_rescheduling/service.py

---
<br><br>
---
Fix logical issue when get all issue-rescheduling
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Fix logical issue when get all issue-rescheduling

---

src/agent/tool.py

…te with llm
---
<br><br>
---
- To request recommendation of rescheduling, contents must be json.
- So, expressed project, issue object as json
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Make serializable json object (project, issue) when communicating with llm

---

src/agent/schemas.py

---
<br><br>
---
- There was wrong typo in classmethod of FeedbackRes
- So, Amend it.
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Amend wrong typo in FeedbackRes

---

src/common/util/permissions.py
src/project/repository.py
src/project/service.py

---
close #207 
<br><br>
---
Add function to update project name
Change repository code for updates from add to merge (db.merge(project)
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

fix: Add function to update project name

---

src/agent/schemas.py

---
<br><br>
---
- Change type of assignees(string) to list at RecomendAssigneeRes
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Amend type of assignees at RecommendAssigneeRes

---

src/agent/schemas.py

---
<br><br>
---
- There was errror because input type(str) is not valid for schemas
- Change type of issue title(list[str]) to string.
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Amend type of issue title at RecommendAssigneeRes

---

src/auth/service.py

---
<br><br>
---
Change samesite value to lax from none at auth cookie setting
<br><br>
---
<br><br>
---
<br><br>
---
<br><br>

hotfix: Fix auth samesite issue
